branch-defaults:
  master:
    environment: null
global:
  application_name: NMBus2httpV1
  default_ec2_keyname: numo-labs
  default_platform: Node.js
  default_region: eu-west-1
  profile: null
  sc: git
